apiVersion: v1
kind: Service
metadata:
  name: tekton-demo
  labels:
    app: tekton-demo
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: tekton-demo